---
# tasks file for base-config
- name: enable repos
  template:
    src: repos_template.j2
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

- name: install base tools and packages
  yum:
    name:
      - httpie
      - python-pip
    state: latest